### ISSUE TITLE
play file (playf)

### ISSUE THREAD

**Issue by CarcaPax** [SeverinoDaDalt/s-bot#3]
Funcion que te repoduzca un fichero que se encuentra en la carpeta poniendo solo su nombre asi no hay necesidad de poner el url siempre . EJ: "!playf pokemon"

**Comment by SeverinoDaDalt** [comment]
En vez de esto, lo que he hecho es pasar de tener la función `play` a dos funciones diferentes:
- `!download <URL_DE_VIDEO_DE_YT> <NAME>` que descarga el audio del video <URL_DE_VIDEO_DE_YT> y lo guarda con el nombre <NAME>.mp3.
- `!play <NAME> <optional: N_TIMES>`: que reproduce la canción <NAME>.mp3 (si existe) <N_TIMES> veces (por defecto 1). Ya no se pueden reproducir canciones no descargadas.
